using System;
using System.Linq;

namespace SMS2WS_SyncAgent
{
    public static class Enums
    {
        public enum TaxRate
        {
            None     = 0,
            Books    = 1,
            NonBooks = 2
        }

        public enum ProductType
        {
            Unknown = 0,
            Book    = 1,
            NonBook = 2
        }

        public enum Language
        {
            English = 1,
            German  = 2,
            French  = 3,
            Dutch   = 4,
            Italian = 5,
            Spanish = 6
        }

        public enum Country
        {
            Afghanistan                            = 1,
            Albania                                = 2,
            Algeria                                = 3,
            AmericanSamoa                          = 4,
            Andorra                                = 5,
            Angola                                 = 6,
            Anguilla                               = 7,
            Antarctica                             = 8,
            AntiguaAndBarbuda                      = 9,
            Argentina                              = 10,
            Armenia                                = 11,
            Aruba                                  = 12,
            Australia                              = 13,
            Austria                                = 14,
            Azerbaijan                             = 15,
            Bahamas                                = 16,
            Bahrain                                = 17,
            Bangladesh                             = 18,
            Barbados                               = 19,
            Belarus                                = 20,
            Belgium                                = 21,
            Belize                                 = 22,
            Benin                                  = 23,
            Bermuda                                = 24,
            Bhutan                                 = 25,
            Bolivia                                = 26,
            BosniaAndHerzegovina                   = 27,
            Botswana                               = 28,
            BouvetIsland                           = 29,
            Brazil                                 = 30,
            BritishIndianOceanTerritory            = 31,
            BruneiDarussalam                       = 32,
            Bulgaria                               = 33,
            BurkinaFaso                            = 34,
            Burundi                                = 35,
            Cambodia                               = 36,
            Cameroon                               = 37,
            Canada                                 = 38,
            CapeVerde                              = 39,
            CaymanIslands                          = 40,
            CentralAfricanRepublic                 = 41,
            Chad                                   = 42,
            Chile                                  = 43,
            China                                  = 44,
            ChristmasIsland                        = 45,
            CocosIslands                           = 46,
            Colombia                               = 47,
            Comoros                                = 48,
            Congo                                  = 49,
            CongoDemocraticRepublic                = 50,
            CookIslands                            = 51,
            CostaRica                              = 52,
            CoteDIvoire                            = 53,
            Croatia                                = 54,
            Cuba                                   = 55,
            Cyprus                                 = 56,
            CzechRepublic                          = 57,
            Denmark                                = 58,
            Djibouti                               = 59,
            Dominica                               = 60,
            DominicanRepublic                      = 61,
            Ecuador                                = 62,
            Egypt                                  = 63,
            ElSalvador                             = 64,
            EquatorialGuinea                       = 65,
            Eritrea                                = 66,
            Estonia                                = 67,
            Ethiopia                               = 68,
            FalklandIslandsMalvinas                = 69,
            FaroeIslands                           = 70,
            Fiji                                   = 71,
            Finland                                = 72,
            France                                 = 73,
            FrenchGuiana                           = 74,
            FrenchPolynesia                        = 75,
            FrenchSouthernTerritories              = 76,
            Gabon                                  = 77,
            Gambia                                 = 78,
            Georgia                                = 79,
            Germany                                = 80,
            Ghana                                  = 81,
            Gibraltar                              = 82,
            Greece                                 = 83,
            Greenland                              = 84,
            Grenada                                = 85,
            Guadeloupe                             = 86,
            Guam                                   = 87,
            Guatemala                              = 88,
            Guinea                                 = 89,
            GuineaBissau                           = 90,
            Guyana                                 = 91,
            Haiti                                  = 92,
            HeardIslandAndMcDonaldIslands          = 93,
            HolySeeVaticanCityState                = 94,
            Honduras                               = 95,
            HongKong                               = 96,
            Hungary                                = 97,
            Iceland                                = 98,
            India                                  = 99,
            Indonesia                              = 100,
            IranIslamicRepublic                    = 101,
            Iraq                                   = 102,
            Ireland                                = 103,
            Israel                                 = 104,
            Italy                                  = 105,
            Jamaica                                = 106,
            Japan                                  = 107,
            Jordan                                 = 108,
            Kazakhstan                             = 109,
            Kenya                                  = 110,
            Kiribati                               = 111,
            KoreaDemocraticPeoplesRepublic         = 112,
            KoreaRepublic                          = 113,
            Kuwait                                 = 114,
            Kyrgyzstan                             = 115,
            LaoPeoplesDemocraticRepublic           = 116,
            Latvia                                 = 117,
            Lebanon                                = 118,
            Lesotho                                = 119,
            Liberia                                = 120,
            LibyanArabJamahiriya                   = 121,
            Liechtenstein                          = 122,
            Lithuania                              = 123,
            Luxembourg                             = 124,
            Macao                                  = 125,
            Macedonia                              = 126,
            Madagascar                             = 127,
            Malawi                                 = 128,
            Malaysia                               = 129,
            Maldives                               = 130,
            Mali                                   = 131,
            Malta                                  = 132,
            MarshallIslands                        = 133,
            Martinique                             = 134,
            Mauritania                             = 135,
            Mauritius                              = 136,
            Mayotte                                = 137,
            Mexico                                 = 138,
            MicronesiaFederatedStates              = 139,
            MoldovaRepublic                        = 140,
            Monaco                                 = 141,
            Mongolia                               = 142,
            Montserrat                             = 143,
            Morocco                                = 144,
            Mozambique                             = 145,
            Myanmar                                = 146,
            Namibia                                = 147,
            Nauru                                  = 148,
            Nepal                                  = 149,
            Netherlands                            = 150,
            NetherlandsAntilles                    = 151,
            NewCaledonia                           = 152,
            NewZealand                             = 153,
            Nicaragua                              = 154,
            Niger                                  = 155,
            Nigeria                                = 156,
            Niue                                   = 157,
            NorfolkIsland                          = 158,
            NorthernMarianaIslands                 = 159,
            Norway                                 = 160,
            Oman                                   = 161,
            Pakistan                               = 162,
            Palau                                  = 163,
            PalestinianTerritory                   = 164,
            Panama                                 = 165,
            PapuaNewGuinea                         = 166,
            Paraguay                               = 167,
            Peru                                   = 168,
            Philippines                            = 169,
            Pitcairn                               = 170,
            Poland                                 = 171,
            Portugal                               = 172,
            PuertoRico                             = 173,
            Qatar                                  = 174,
            Reunion                                = 175,
            Romania                                = 176,
            RussianFederation                      = 177,
            Rwanda                                 = 178,
            SaintHelena                            = 179,
            SaintKittsandNevis                     = 180,
            SaintLucia                             = 181,
            SaintPierreandMiquelon                 = 182,
            SaintVincentandtheGrenadines           = 183,
            Samoa                                  = 184,
            SanMarino                              = 185,
            SaoTomeandPrincipe                     = 186,
            SaudiArabia                            = 187,
            Senegal                                = 188,
            SerbiaandMontenegro                    = 189,
            Seychelles                             = 190,
            SierraLeone                            = 191,
            Singapore                              = 192,
            Slovakia                               = 193,
            Slovenia                               = 194,
            SolomonIslands                         = 195,
            Somalia 							   = 196,
            SouthAfrica 						   = 197,
            SouthGeorgiaAndTheSouthSandwichIslands = 198,
            Spain                                  = 199,
            SriLanka                               = 200,
            Sudan                                  = 201,
            Suriname                               = 202,
            SvalbardAndJanMayen                    = 203,
            Swaziland                              = 204,
            Sweden                                 = 205,
            Switzerland                            = 206,
            SyrianArabRepublic                     = 207,
            Taiwan                                 = 208,
            Tajikistan                             = 209,
            Tanzania                               = 210,
            Thailand                               = 211,
            TimorLeste                             = 212,
            Togo                                   = 213,
            Tokelau                                = 214,
            Tonga                                  = 215,
            TrinidadAndTobago                      = 216,
            Tunisia                                = 217,
            Turkey                                 = 218,
            Turkmenistan                           = 219,
            TurksAndCaicosIslands                  = 220,
            Tuvalu                                 = 221,
            Uganda                                 = 222,
            Ukraine                                = 223,
            UnitedArabEmirates                     = 224,
            UnitedKingdom                          = 225,
            UnitedStates                           = 226,
            UnitedStatesMinorOutlyingIslands       = 227,
            Uruguay                                = 228,
            Uzbekistan                             = 229,
            Vanuatu                                = 230,
            Venezuela                              = 231,
            VietNam                                = 232,
            VirginIslandsBritish                   = 233,
            VirginIslandsUS                        = 234,
            WallisAndFutuna                        = 235,
            WesternSahara                          = 236,
            Yemen                                  = 237,
            Zambia                                 = 238,
            Zimbabwe                               = 239
        }

        public enum Logfield
        {
            Flag                      = 0,
            ProductId                 = 1,
            SongSortOrder             = 2,
            SongTitle                 = 3,
            //Omschrijving              = 3,
            InstrumentId              = 4,
            //Rubriek                   = 4,
            AuthorId                  = 5,
            ManufacturerId            = 6,
            // Fabrikant                 = 6,
            SupplierId                = 7,
            ReferenceNumber           = 8,
            Isbn                      = 9,
            Ismn                      = 10,
            Upc                       = 11,
            Ean                       = 12,
            //PrijsAK_in_VV             = 13,
            //PrijsAK_in_EUR            = 14,
            //PrijsVK_in_VV             = 15,
            //AdviesPrijs_in_VV         = 16,
            //AdviesPrijs_in_EUR        = 17,
            //PrijsVk_Basis             = 18,
            //PrijsVK_Korting           = 19,
            SalesPrice                = 20,
            //VVCode                    = 21,
            //Korting                   = 22,
            //Prijscode                 = 23,
            //PrijswijzigDttm           = 24,
            UpdateDttm                = 25,
            //StockopnameDttm           = 26,
            InputDttm                 = 27,
            CreateDttm                = 28,
            //VerkoopDttm               = 29,
            StockQty_G                = 30,
            StockQty_A                = 31,
            StockQty_Ext              = 32,
            //TFTaantal                 = 33,
            //MinimumStock              = 34,
            //FlagListing               = 35,
            //LabelTitel                = 36,
            //Stocklocatie              = 37,
            //Stockopname_A_Dttm        = 38,
            //PackQty                   = 39,
            //Nota                      = 40,
            //PrintPrijs                = 41,
            //Status_OP                 = 42,
            //Status_OPDatum            = 43,
            //Status_OPNota             = 44,
            //Status_Disc               = 45,
            //Status_DiscDatum          = 46,
            //Status_DiscNota           = 47,
            //Status_NmB                = 48,
            //Status_NmBDatum           = 49,
            //Status_NmBNota            = 50,
            //ExternalProductInfoURL    = 51,
            PublicProductName_EN      = 52,
            ActiveInWebshop           = 53,
            HighlightOnHome           = 54,
            Promotion                 = 55,
            TeacherDiscount           = 56,
            ResellerDiscount          = 57,
            SeriesId                  = 58,
            LanguageId                = 59,
            Pages                     = 60,
            BindingId                 = 61,
            Length                    = 62,
            Width                     = 63,
            Height                    = 64,
            Weight                    = 65,
            GradeLevel                = 66,
            ProductCategory           = 67,
            //PrintLabelQty             = 68,
            Description_NL            = 69,
            //RefNr2                    = 70,
            //StocklocatieNota          = 71,
            MinimumOrderQty           = 72,
            //SyncInstructions          = 73,
            //Stocklocatie_Prev         = 74,
            //StockopnameQty            = 75,
            //InputQty                  = 76,
            //Stockaantal_Prev          = 77,
            DeleteDttm                = 78,
            //MergedArtNr               = 79,
            //TFTBonNr                  = 80,
            //PrintLabel                = 81,
            //OutputQty                 = 82,
            ExternalStock             = 83,
            //POSAlert                  = 84,
            //ShowPOSAlert              = 85,
            //ExternalStockID           = 86,
            Subtitle_NL               = 87,
            ArrangerId                = 88,
            InternalStock             = 89,
            ProductPictureFilename    = 90,
            ProductPictureFileChanged = 91,
            ProductTypeId             = 92,
            TaxRateId                 = 93,
            BestSeller                = 94,
            PublicProductName_NL      = 95,
            SearchKeywords            = 96,
            WebshopTeacherDiscount    = 97,
            WebshopResellerDiscount   = 98,
            StorePickupOnly           = 99
        }

        //the UpdateActions enum contains the various actions in the order in which they need to be processed
        // 1. lookup updates - new lookup values will be created before the product is created
        // 2. product updates
        // 3. lookup deletes - lookup values will be deleted after that eventual references in the product have been updated
        // 4. product deletes
        // 5. customer updates - new customers will be created before any other action is performed on them
        // 6. customer status approvals and password resets
        // 7. customer deletes
        public enum UpdateActions
        {
            author_update,
            binding_update,
            instrument_update,
            manufacturer_update,
            supplier_update,
            productSeries_update,
            productCategory_update,
            product_update,
            author_delete,
            binding_delete,
            instrument_delete,
            manufacturer_delete,
            supplier_delete,
            productSeries_delete,
            productCategory_delete,
            product_delete,
            productCategory_product_count,
            customer_SMS2WS_update,
            customer_SMS2WS_teacher_approval,
            customer_SMS2WS_password_reset,
            customer_SMS2WS_delete,
            customer_WS2SMS_update
        }


        public static TEnum GetHighestValue<TEnum>()
        {
            return Enum.GetValues(typeof(TEnum)).Cast<TEnum>().Max();
        }
    }
}

